services:
  # Backend API service
  - type: web
    name: teachease-backend
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: .onrender.com,localhost,127.0.0.1
      - key: DATABASE_URL
        fromDatabase:
          name: teachease-db
          property: connectionString
      - key: CORS_ALLOWED_ORIGINS
        value: https://frontend-smuk.onrender.com,https://teachease-frontend.onrender.com,http://localhost:5173
      - key: PYTHON_VERSION
        value: 3.11.8

# Database
databases:
  - name: teachease-db
    plan: free
