# Generated by Django 4.2.7 on 2025-04-14 08:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الصف')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف الصف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'صف',
                'verbose_name_plural': 'صفوف',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الفصل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'فصل',
                'verbose_name_plural': 'فصول',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المادة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('parent_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_subjects', to='api.subject', verbose_name='المادة الأساسية')),
            ],
            options={
                'verbose_name': 'مادة',
                'verbose_name_plural': 'مواد',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الطالب')),
                ('image', models.ImageField(blank=True, null=True, upload_to='students/', verbose_name='صورة الطالب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='api.class', verbose_name='الصف')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='api.section', verbose_name='الفصل')),
            ],
            options={
                'verbose_name': 'طالب',
                'verbose_name_plural': 'طلاب',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, 'الأحد'), (1, 'الإثنين'), (2, 'الثلاثاء'), (3, 'الأربعاء'), (4, 'الخميس')], verbose_name='اليوم')),
                ('period', models.IntegerField(choices=[(1, 'الحصة الأولى'), (2, 'الحصة الثانية'), (3, 'الحصة الثالثة'), (4, 'الحصة الرابعة'), (5, 'الحصة الخامسة'), (6, 'الحصة السادسة'), (7, 'الحصة السابعة')], verbose_name='الحصة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='api.class', verbose_name='الصف')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='api.section', verbose_name='الفصل')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='api.subject', verbose_name='المادة')),
            ],
            options={
                'verbose_name': 'جدول دراسي',
                'verbose_name_plural': 'جداول دراسية',
                'ordering': ['day', 'period'],
                'unique_together': {('day', 'period', 'class_name', 'section')},
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='نص الملاحظة')),
                ('type', models.CharField(choices=[('positive', 'إيجابية'), ('negative', 'سلبية')], default='positive', max_length=10, verbose_name='نوع الملاحظة')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='التاريخ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='api.schedule', verbose_name='الحصة')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='api.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'ملاحظة',
                'verbose_name_plural': 'ملاحظات',
                'ordering': ['-date', 'student__name'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('theory', 'نظري'), ('practical', 'تطبيق'), ('participation', 'مشاركة'), ('final', 'نهائي')], max_length=15, verbose_name='نوع الدرجة')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='الدرجة')),
                ('max_score', models.PositiveIntegerField(default=100, verbose_name='الدرجة القصوى')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='التاريخ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='api.student', verbose_name='الطالب')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='api.subject', verbose_name='المادة')),
            ],
            options={
                'verbose_name': 'درجة',
                'verbose_name_plural': 'درجات',
                'ordering': ['-date', 'student__name'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان الواجب')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف الواجب')),
                ('due_date', models.DateField(verbose_name='تاريخ التسليم')),
                ('score', models.PositiveIntegerField(default=10, verbose_name='الدرجة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='api.schedule', verbose_name='الحصة')),
            ],
            options={
                'verbose_name': 'واجب',
                'verbose_name_plural': 'واجبات',
                'ordering': ['-due_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='التاريخ')),
                ('status', models.CharField(choices=[('present', 'حاضر'), ('absent', 'غائب')], default='present', max_length=10, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='api.schedule', verbose_name='الحصة')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='api.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'حضور',
                'verbose_name_plural': 'حضور',
                'ordering': ['-date', 'student__name'],
                'unique_together': {('student', 'schedule', 'date')},
            },
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('submitted', 'تم التسليم'), ('not_submitted', 'لم يتم التسليم')], default='not_submitted', max_length=15, verbose_name='حالة التسليم')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='الدرجة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='api.assignment', verbose_name='الواجب')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='api.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'تسليم واجب',
                'verbose_name_plural': 'تسليمات الواجبات',
                'ordering': ['-updated_at'],
                'unique_together': {('student', 'assignment')},
            },
        ),
    ]
