# Generated by Django 4.2.7 on 2025-04-14 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='subject_info',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم المادة'),
        ),
    ]
