# Generated by Django 4.2.7 on 2025-04-14 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_assignment_subject_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='subject_info',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم المادة'),
        ),
    ]
