# Generated by Django 4.2.7 on 2025-04-14 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_assignment_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhiteboardDrawing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الرسم')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف الرسم')),
                ('data', models.TextField(verbose_name='بيانات الرسم')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='whiteboard_thumbnails/', verbose_name='صورة مصغرة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'رسم السبورة',
                'verbose_name_plural': 'رسومات السبورة',
                'ordering': ['-created_at'],
            },
        ),
    ]
