# Generated by Django 4.2.7 on 2025-04-15 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_whiteboarddrawing'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='المعلم', max_length=100, verbose_name='اسم المستخدم')),
                ('user_email', models.EmailField(default='teacher@example.com', max_length=254, verbose_name='البريد الإلكتروني')),
                ('user_avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='الصورة الشخصية')),
                ('time_system', models.CharField(choices=[('regular', 'النظام العادي'), ('summer', 'النظام الصيفي'), ('ramadan', 'نظام رمضان')], default='regular', max_length=10, verbose_name='النظام الزمني')),
                ('show_notifications', models.BooleanField(default=True, verbose_name='تفعيل التنبيهات')),
                ('notification_time', models.IntegerField(default=5, verbose_name='وقت التنبيه قبل نهاية الحصة (بالدقائق)')),
                ('periods_data', models.TextField(default='[]', verbose_name='بيانات الحصص')),
                ('dark_mode', models.BooleanField(default=False, verbose_name='الوضع الليلي')),
                ('font_size', models.CharField(choices=[('small', 'صغير'), ('medium', 'متوسط'), ('large', 'كبير')], default='medium', max_length=10, verbose_name='حجم الخط')),
                ('primary_color', models.CharField(default='#1976D2', max_length=20, verbose_name='اللون الرئيسي')),
                ('school_name', models.CharField(default='مدرسة التعليم الإسلامي', max_length=200, verbose_name='اسم المدرسة')),
                ('school_logo', models.ImageField(blank=True, null=True, upload_to='school/', verbose_name='شعار المدرسة')),
                ('academic_year', models.CharField(default='1445-1446', max_length=20, verbose_name='العام الدراسي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'إعدادات النظام',
                'verbose_name_plural': 'إعدادات النظام',
            },
        ),
    ]
