# Generated by Django 4.2.7 on 2025-04-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_systemsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان التنبيه')),
                ('message', models.TextField(verbose_name='نص التنبيه')),
                ('type', models.CharField(choices=[('info', 'معلومات'), ('success', 'نجاح'), ('warning', 'تحذير'), ('error', 'خطأ')], default='info', max_length=10, verbose_name='نوع التنبيه')),
                ('is_read', models.BooleanField(default=False, verbose_name='تمت القراءة')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='رابط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'تنبيه',
                'verbose_name_plural': 'تنبيهات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='SystemSettings',
        ),
    ]
