# Generated by Django 4.2.7 on 2025-04-18 11:44

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_notification_delete_systemsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(default='active', max_length=20, verbose_name='حالة الطالب'),
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='students/', validators=[api.models.validate_image_size], verbose_name='صورة الطالب'),
        ),
    ]
