# Generated by Django 4.2.7 on 2025-04-18 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_student_status_alter_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='type',
            field=models.CharField(choices=[('theory', 'نظري'), ('practical', 'تطبيق'), ('participation', 'مشاركة'), ('quran', 'القرآن'), ('final', 'نهائي')], max_length=15, verbose_name='نوع الدرجة'),
        ),
    ]
