# Generated by Django 4.2.7 on 2025-04-19 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_add_indexes'),
        ('api', '0010_alter_grade_type'),
    ]

    operations = [
    ]
